name: Build eiwd

on:
  push:
    branches:
      - main
    paths:
      - '**/*'               # Include all files
      - '!README.md'          # Exclude README.md

jobs:
  build:
    runs-on: ubuntu-latest  # This is to run the GitHub Actions 
    container:
      image: debian:stable  
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name:  install dependecies
      run: |
       bash build.sh
       ver=$(cat ver)
       upload=$(realpath iwd-$ver/src/iwd)
       echo "FILE1=${upload}" >> $GITHUB_ENV 
       echo "ver=$ver" >> $GITHUB_ENV 

    - name: Create GitHub Release and Upload ZIP
      uses: softprops/action-gh-release@v2
      with:
          tag_name: ${{ env.ver }}
          files: |
              ${{ env.FILE1 }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
       
       
      
